services:
  db:
    image: mysql:8.0
    container_name: bidding-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bidding_system
    ports:
      - "3307:3306"
    volumes:
      - /home/bidding-system/mysql-data:/var/lib/mysql
      - /home/bidding-system/database-scripts/database.sql:/docker-entrypoint-initdb.d/database.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  backend:
    image: bidding-backend:latest
    container_name: bidding-backend
    restart: always
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bidding_system?useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db

  frontend:
    image: bidding-frontend:latest
    container_name: bidding-frontend
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - backend
